spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kakaotest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false

