import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.scss";

const notoSansKr = Noto_Sans_KR({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "We Sync, 위싱",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
